import * as yup from "yup";
const countries = [
  { code: "AD", label: "أندورا", phone: "376" },
  {
    code: "AE",
    label: "الإمارات العربية المتحدة",
    phone: "971",
  },
  { code: "AF", label: "أفغانستان", phone: "93" },
  {
    code: "AG",
    label: "أنتيغوا وبربودا",
    phone: "1-268",
  },
  { code: "AI", label: "أنجويلا", phone: "1-264" },
  { code: "AL", label: "ألبانيا", phone: "355" },
  { code: "AM", label: "أرمينيا", phone: "374" },
  { code: "AO", label: "أنغولا", phone: "244" },
  { code: "AQ", label: "أنتاركتيكا", phone: "672" },
  { code: "AR", label: "الأرجنتين", phone: "54" },
  { code: "AS", label: "ساموا الأمريكية", phone: "1-684" },
  { code: "AT", label: "النمسا", phone: "43" },
  {
    code: "AU",
    label: "أستراليا",
    phone: "61",
    suggested: true,
  },
  { code: "AW", label: "أروبا", phone: "297" },
  { code: "AX", label: "جزر آلاند", phone: "358" },
  { code: "AZ", label: "أذربيجان", phone: "994" },
  {
    code: "BA",
    label: "البوسنة والهرسك",
    phone: "387",
  },
  { code: "BB", label: "بربادوس", phone: "1-246" },
  { code: "BD", label: "بنغلاديش", phone: "880" },
  { code: "BE", label: "بلجيكا", phone: "32" },
  { code: "BF", label: "بوركينا فاسو", phone: "226" },
  { code: "BG", label: "بلغاريا", phone: "359" },
  { code: "BH", label: "البحرين", phone: "973" },
  { code: "BI", label: "بوروندي", phone: "257" },
  { code: "BJ", label: "بنين", phone: "229" },
  { code: "BL", label: "سان بارتيلمي", phone: "590" },
  { code: "BM", label: "برمودا", phone: "1-441" },
  { code: "BN", label: "بروناي", phone: "673" },
  { code: "BO", label: "بوليفيا", phone: "591" },
  { code: "BR", label: "البرازيل", phone: "55" },
  { code: "BS", label: "الباهاما", phone: "1-242" },
  { code: "BT", label: "بوتان", phone: "975" },
  { code: "BV", label: "جزيرة بوفيه", phone: "47" },
  { code: "BW", label: "بوتسوانا", phone: "267" },
  { code: "BY", label: "روسيا البيضاء", phone: "375" },
  { code: "BZ", label: "بليز", phone: "501" },
  {
    code: "CA",
    label: "كندا",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    label: "جزر كوكوس (كيلينغ)",
    phone: "61",
  },
  {
    code: "CD",
    label: "جمهورية الكونغو الديمقراطية",
    phone: "243",
  },
  {
    code: "CF",
    label: "جمهورية أفريقيا الوسطى",
    phone: "236",
  },
  {
    code: "CG",
    label: "جمهورية الكونغو",
    phone: "242",
  },
  { code: "CH", label: "سويسرا", phone: "41" },
  { code: "CI", label: "ساحل العاج", phone: "225" },
  { code: "CK", label: "جزر كوك", phone: "682" },
  { code: "CL", label: "تشيلي", phone: "56" },
  { code: "CM", label: "الكاميرون", phone: "237" },
  { code: "CN", label: "الصين", phone: "86" },
  { code: "CO", label: "كولومبيا", phone: "57" },
  { code: "CR", label: "كوستاريكا", phone: "506" },
  { code: "CU", label: "كوبا", phone: "53" },
  { code: "CV", label: "الرأس الأخضر", phone: "238" },
  { code: "CW", label: "كوراساو", phone: "599" },
  { code: "CX", label: "جزيرة الكريسماس", phone: "61" },
  { code: "CY", label: "قبرص", phone: "357" },
  { code: "CZ", label: "التشيك", phone: "420" },
  {
    code: "DE",
    label: "ألمانيا",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", label: "جيبوتي", phone: "253" },
  { code: "DK", label: "الدنمارك", phone: "45" },
  { code: "DM", label: "دومينيكا", phone: "1-767" },
  {
    code: "DO",
    label: "جمهورية الدومينيكان",
    phone: "1-809",
  },
  { code: "DZ", label: "الجزائر", phone: "213" },
  { code: "EC", label: "الإكوادور", phone: "593" },
  { code: "EE", label: "إستونيا", phone: "372" },
  { code: "EG", label: "مصر", phone: "20" },
  { code: "EH", label: "الصحراء الغربية", phone: "212" },
  { code: "ER", label: "إريتريا", phone: "291" },
  { code: "ES", label: "إسبانيا", phone: "34" },
  { code: "ET", label: "إثيوبيا", phone: "251" },
  { code: "FI", label: "فنلندا", phone: "358" },
  { code: "FJ", label: "فيجي", phone: "679" },
  {
    code: "FK",
    label: "جزر فوكلاند (مالفيناس)",
    phone: "500",
  },
  {
    code: "FM",
    label: "ميكرونيزيا، ولايات فدرالية من",
    phone: "691",
  },
  { code: "FO", label: "جزر فارو", phone: "298" },
  {
    code: "FR",
    label: "فرنسا",
    phone: "33",
    suggested: true,
  },
  { code: "GA", label: "الجابون", phone: "241" },
  { code: "GB", label: "المملكة المتحدة", phone: "44" },
  { code: "GD", label: "غرينادا", phone: "1-473" },
  { code: "GE", label: "جورجيا", phone: "995" },
  { code: "GF", label: "غويانا الفرنسية", phone: "594" },
  { code: "GG", label: "غيرنسي", phone: "44" },
  { code: "GH", label: "غانا", phone: "233" },
  { code: "GI", label: "جبل طارق", phone: "350" },
  { code: "GL", label: "غرينلاند", phone: "299" },
  { code: "GM", label: "غامبيا", phone: "220" },
  { code: "GN", label: "غينيا", phone: "224" },
  { code: "GP", label: "غوادلوب", phone: "590" },
  { code: "GQ", label: "غينيا الاستوائية", phone: "240" },
  { code: "GR", label: "اليونان", phone: "30" },
  {
    code: "GS",
    label: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    phone: "500",
  },
  { code: "GT", label: "غواتيمالا", phone: "502" },
  { code: "GU", label: "غوام", phone: "1-671" },
  { code: "GW", label: "غينيا بيساو", phone: "245" },
  { code: "GY", label: "غيانا", phone: "592" },
  { code: "HK", label: "هونغ كونغ", phone: "852" },
  {
    code: "HM",
    label: "جزيرة هيرد وجزر ماكدونالد",
    phone: "672",
  },
  { code: "HN", label: "هندوراس", phone: "504" },
  { code: "HR", label: "كرواتيا", phone: "385" },
  { code: "HT", label: "هايتي", phone: "509" },
  { code: "HU", label: "هنغاريا", phone: "36" },
  { code: "ID", label: "إندونيسيا", phone: "62" },
  { code: "IE", label: "أيرلندا", phone: "353" },
  { code: "IL", label: "إسرائيل", phone: "972" },
  { code: "IM", label: "جزيرة مان", phone: "44" },
  { code: "IN", label: "الهند", phone: "91" },
  {
    code: "IO",
    label: "إقليم المحيط الهندي البريطاني",
    phone: "246",
  },
  { code: "IQ", label: "العراق", phone: "964" },
  { code: "IR", label: "إيران، جمهورية", phone: "98" },
  { code: "IS", label: "آيسلندا", phone: "354" },
  { code: "IT", label: "إيطاليا", phone: "39" },
  { code: "JE", label: "جيرسي", phone: "44" },
  { code: "JM", label: "جامايكا", phone: "1-876" },
  { code: "JO", label: "الأردن", phone: "962" },
  {
    code: "JP",
    label: "اليابان",
    phone: "81",
    suggested: true,
  },
  { code: "KE", label: "كينيا", phone: "254" },
  { code: "KG", label: "قيرغيزستان", phone: "996" },
  { code: "KH", label: "كمبوديا", phone: "855" },
  { code: "KI", label: "كيريباتي", phone: "686" },
  { code: "KM", label: "جزر القمر", phone: "269" },
  {
    code: "KN",
    label: "سانت كيتس ونيفيس",
    phone: "1-869",
  },
  {
    code: "KP",
    label: "كوريا الشمالية",
    phone: "850",
  },
  { code: "KR", label: "كوريا الجنوبية", phone: "82" },
  { code: "KW", label: "الكويت", phone: "965" },
  { code: "KY", label: "جزر كايمان", phone: "1-345" },
  { code: "KZ", label: "كازاخستان", phone: "7" },
  {
    code: "LA",
    label: "جمهورية لاو الديمقراطية الشعبية",
    phone: "856",
  },
  { code: "LB", label: "لبنان", phone: "961" },
  { code: "LC", label: "سانت لوسيا", phone: "1-758" },
  { code: "LI", label: "ليختنشتاين", phone: "423" },
  { code: "LK", label: "سريلانكا", phone: "94" },
  { code: "LR", label: "ليبيريا", phone: "231" },
  { code: "LS", label: "ليسوتو", phone: "266" },
  { code: "LT", label: "ليتوانيا", phone: "370" },
  { code: "LU", label: "لوكسمبورغ", phone: "352" },
  { code: "LV", label: "لاتفيا", phone: "371" },
  { code: "LY", label: "ليبيا", phone: "218" },
  { code: "MA", label: "المغرب", phone: "212" },
  { code: "MC", label: "موناكو", phone: "377" },
  {
    code: "MD",
    label: "جمهورية مولدوفا",
    phone: "373",
  },
  { code: "ME", label: "الجبل الأسود", phone: "382" },
  {
    code: "MF",
    label: "سانت مارتن (الجزء الفرنسي)",
    phone: "590",
  },
  { code: "MG", label: "مدغشقر", phone: "261" },
  { code: "MH", label: "جزر مارشال", phone: "692" },
  {
    code: "MK",
    label: "مقدونيا، جمهورية يوغوسلافيا السابقة",
    phone: "389",
  },
  { code: "ML", label: "مالي", phone: "223" },
  { code: "MM", label: "ميانمار", phone: "95" },
  { code: "MN", label: "منغوليا", phone: "976" },
  { code: "MO", label: "مكاو", phone: "853" },
  { code: "MP", label: "جزر ماريانا الشمالية", phone: "1-670" },
  { code: "MQ", label: "مارتينيك", phone: "596" },
  { code: "MR", label: "موريتانيا", phone: "222" },
  { code: "MS", label: "مونتسرات", phone: "1-664" },
  { code: "MT", label: "مالطا", phone: "356" },
  { code: "MU", label: "موريشيوس", phone: "230" },
  { code: "MV", label: "جزر المالديف", phone: "960" },
  { code: "MW", label: "ملاوي", phone: "265" },
  { code: "MX", label: "المكسيك", phone: "52" },
  { code: "MY", label: "ماليزيا", phone: "60" },
  { code: "MZ", label: "موزمبيق", phone: "258" },
  { code: "NA", label: "ناميبيا", phone: "264" },
  { code: "NC", label: "كاليدونيا الجديدة", phone: "687" },
  { code: "NE", label: "النيجر", phone: "227" },
  { code: "NF", label: "جزيرة نورفولك", phone: "672" },
  { code: "NG", label: "نيجيريا", phone: "234" },
  { code: "NI", label: "نيكاراغوا", phone: "505" },
  { code: "NL", label: "هولندا", phone: "31" },
  { code: "NO", label: "النرويج", phone: "47" },
  { code: "NP", label: "نيبال", phone: "977" },
  { code: "NR", label: "ناورو", phone: "674" },
  { code: "NU", label: "نيوي", phone: "683" },
  { code: "NZ", label: "نيوزيلندا", phone: "64" },
  { code: "OM", label: "عمان", phone: "968" },
  { code: "PA", label: "بنما", phone: "507" },
  { code: "PE", label: "بيرو", phone: "51" },
  { code: "PF", label: "بولينيزيا الفرنسية", phone: "689" },
  { code: "PG", label: "بابوا غينيا الجديدة", phone: "675" },
  { code: "PH", label: "الفلبين", phone: "63" },
  { code: "PK", label: "باكستان", phone: "92" },
  { code: "PL", label: "بولندا", phone: "48" },
  { code: "PM", label: "سان بيير وميكولون", phone: "508" },
  { code: "PN", label: "جزر بيتكيرن", phone: "64" },
  { code: "PR", label: "بورتوريكو", phone: "1-787" },
  { code: "PS", label: "فلسطين", phone: "970" },
  {
    code: "PT",
    label: "البرتغال",
    phone: "351",
    suggested: true,
  },
  { code: "PW", label: "بالاو", phone: "680" },
  { code: "PY", label: "باراغواي", phone: "595" },
  { code: "QA", label: "قطر", phone: "974" },
  {
    code: "RE",
    label: "روينيون",
    phone: "262",
  },
  { code: "RO", label: "رومانيا", phone: "40" },
  { code: "RS", label: "صربيا", phone: "381" },
  { code: "RU", label: "روسيا", phone: "7" },
  { code: "RW", label: "رواندا", phone: "250" },
  { code: "SA", label: "المملكة العربية السعودية", phone: "966" },
  { code: "SB", label: "جزر سليمان", phone: "677" },
  { code: "SC", label: "سيشيل", phone: "248" },
  { code: "SD", label: "السودان", phone: "249" },
  { code: "SE", label: "السويد", phone: "46" },
  { code: "SG", label: "سنغافورة", phone: "65" },
  { code: "SH", label: "سانت هيلنا", phone: "290" },
  { code: "SI", label: "سلوفينيا", phone: "386" },
  { code: "SJ", label: "سفالبارد وجان مايان", phone: "47" },
  { code: "SK", label: "سلوفاكيا", phone: "421" },
  { code: "SL", label: "سيراليون", phone: "232" },
  { code: "SM", label: "سان مارينو", phone: "378" },
  { code: "SN", label: "السنغال", phone: "221" },
  { code: "SO", label: "الصومال", phone: "252" },
  { code: "SR", label: "سورينام", phone: "597" },
  { code: "SS", label: "جنوب السودان", phone: "211" },
  { code: "ST", label: "ساو تومي وبرينسيبي", phone: "239" },
  { code: "SV", label: "السلفادور", phone: "503" },
  { code: "SX", label: "سينت مارتن (الجزء الهولندي)", phone: "1-721" },
  { code: "SY", label: "سوريا", phone: "963" },
  { code: "SZ", label: "سوازيلاند", phone: "268" },
  {
    code: "TC",
    label: "جزر الترك وجايكوس",
    phone: "1-649",
  },
  { code: "TD", label: "تشاد", phone: "235" },
  { code: "TF", label: "المقاطعات الجنوبية الفرنسية", phone: "262" },
  { code: "TG", label: "توجو", phone: "228" },
  { code: "TH", label: "تايلاند", phone: "66" },
  { code: "TJ", label: "طاجيكستان", phone: "992" },
  { code: "TK", label: "توكيلو", phone: "690" },
  { code: "TL", label: "تيمور الشرقية", phone: "670" },
  { code: "TM", label: "تركمانستان", phone: "993" },
  { code: "TN", label: "تونس", phone: "216" },
  { code: "TO", label: "تونغا", phone: "676" },
  { code: "TR", label: "تركيا", phone: "90" },
  { code: "TT", label: "ترينيداد وتوباغو", phone: "1-868" },
  { code: "TV", label: "توفالو", phone: "688" },
  { code: "TW", label: "تايوان", phone: "886" },
  { code: "TZ", label: "تنزانيا", phone: "255" },
  {
    code: "UA",
    label: "أوكرانيا",
    phone: "380",
  },
  { code: "UG", label: "أوغندا", phone: "256" },
  {
    code: "UM",
    label: "جزر الولايات المتحدة النائية",
    phone: "1",
  },
  { code: "US", label: "الولايات المتحدة", phone: "1", suggested: true },
  { code: "UY", label: "أوروجواي", phone: "598" },
  { code: "UZ", label: "أوزبكستان", phone: "998" },
  { code: "VA", label: "الفاتيكان", phone: "379" },
  {
    code: "VC",
    label: "سانت فنسنت وغرنادين",
    phone: "1-784",
  },
  {
    code: "VE",
    label: "فنزويلا، جمهورية بوليفارية",
    phone: "58",
  },
  { code: "VG", label: "جزر العذراء البريطانية", phone: "1-284" },
  {
    code: "VI",
    label: "جزر العذراء، الولايات المتحدة",
    phone: "1-340",
  },
  { code: "VN", label: "فيتنام", phone: "84" },
  { code: "VU", label: "فانواتو", phone: "678" },
  { code: "WF", label: "والس وفوتونا", phone: "681" },
  { code: "WS", label: "ساموا", phone: "685" },
  { code: "XK", label: "كوسوفو", phone: "383" },
  { code: "YE", label: "اليمن", phone: "967" },
  { code: "YT", label: "مايوت", phone: "262" },
  { code: "ZA", label: "جنوب أفريقيا", phone: "27" },
  {
    code: "ZM",
    label: "زامبيا",
    phone: "260",
  },
  { code: "ZW", label: "زيمبابوي", phone: "263" },
];
const initialCompany = {
  companyName: "",
  investorName: "",
  country: "",
  phone: "",
};

const phoneRegExp = /^01[1250][0-9]{8}$/;

const companySchema = yup.object().shape({
  companyName: yup
    .string()
    .matches(/^[a-zA-Z\u0600-\u06FF\s]*$/, "الاسم يجب أن يحتوي على حروف فقط")
    .min(3, "الاسم لابد أن يكون 3 أحرف على الأقل")
    .required("اسم الشركة مطلوب"),
  investorName: yup
    .string()
    .matches(/^[a-zA-Z\u0600-\u06FF\s]*$/, "الاسم يجب أن يحتوي على حروف فقط")
    .min(3, "الاسم لابد أن يكون 3 أحرف على الأقل")
    .required("اسم المستثمر مطلوب"),
  phone: yup
    .string()
    .matches(phoneRegExp, "رقم الهاتف غير صحيح")
    .required("رقم الهاتف مطلوب"),
  country: yup.string().required("الدولة مطلوب"),
});

export { companySchema, countries, initialCompany };
